export const carts = [
  {
    id: 0,
    topic: 'Web Design',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Без статуса',
  },
  {
    id: 1,
    topic: 'Research',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Без статуса',
  },
  {
    id: 2,
    topic: 'Web Design',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Без статуса',
  },
  {
    id: 3,
    topic: 'Copywriting',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Без статуса',
  },
  {
    id: 4,
    topic: 'Web Design',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Без статуса',
  },
  {
    id: 5,
    topic: 'Research',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Нужно сделать',
  },
  {
    id: 6,
    topic: 'Research',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'В работе',
  },
  {
    id: 7,
    topic: 'Copywriting',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'В работе',
  },
  {
    id: 8,
    topic: 'Web Design',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'В работе',
  },
  {
    id: 9,
    topic: 'Research',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Тестирование',
  },
  {
    id: 10,
    topic: 'Research',
    title: 'Название задачи',
    date: '30.10.23',
    status: 'Готово',
  },
]
